### ISSUE TITLE
AMIs don't exist anymore

### ISSUE THREAD

**Issue by moisei** [justeat/kubernetes-windows-aws-ovs#1]
Hello,
Thank you very much for this great example, it is very useful one. I am sorry, I didn't find any other way to contact you.
I have a question about AMIs. The ones mentioned in the configuration don't exist for my region us-east-1 and windows AMIs don't exist anymore at all.
So I am just wondering which ones should I use, to run the demo app?

I tried EC2 optimized AMI from Amazon for Linux and Windows 2016 for Windows.
Terraform has created all the infrastructure properly but kubernetes are not running on the nodes.
docker ps -a  shows no docker container are even installed.

and one more thing: the S3 bucket doesn't contain any keys. Only bin and files folders.

Thank you in advance,
Moisei.

**Comment by parvez99** [comment]
Hi @moisei wonder if you were able to find an alternative windows AMI to get this working ?

I'm facing the same issue where I cannot find the AMI . Please let me know what's the workaround for this . Thanks very much in advance.

Thanks,
Parvez

**Comment by moisei** [comment]
Hi @parvez99,
Unfortunately, I didn't find any good alternative.

**Comment by parvez99** [comment]
Hi @moisei  Thanks for the reply. I am going to try with Windows Server 2016 AMI and see how it goes.. I tried initially but the gateway node fails health check for the ELB. Not sure what's going wrong but will try few things and let you know.

Did you get this successfully deployed apart from the windows node issue ? 
I can't get the gateway node up and running.

I'm trying the following AMI:

Linux: ami-03998867
Windows: ami-d5eef1b1
Region: London

Your inputs would be very helpful.
Thanks.

**Comment by moisei** [comment]
Hi @parvez99 , just in case it is still relecant, I've user rancher project to build mixed linux/windows k8s cluster on top of windows build 1809 and it works pretty well.
